### ISSUE TITLE
Clone data to new repository

### ISSUE THREAD

**Issue by jakub-moravek** [3KeyCompany/CZERTAINLY-Appliance#1]

**Comment by jakub-moravek** [comment]
- [ ] [CZERTAINLY-Appliance](https://github.com/semik/CZERTAINLY-Appliance)
- [ ] [CZERTAINLY-Appliance-Host-Config](https://github.com/semik/CZERTAINLY-Appliance-Host-Config)
- [ ] [CZERTAINLY-Appliance-RKE2](https://github.com/semik/CZERTAINLY-Appliance-RKE2)
- [ ] [CZERTAINLY-Appliance-Branding](https://github.com/semik/CZERTAINLY-Appliance-Branding)

**Comment by semik** [comment]
I've done some updates. 

* https://github.com/3KeyCompany/CZERTAINLY-Appliance-Branding/pull/1 is still accurate
* https://github.com/3KeyCompany/CZERTAINLY-Appliance-RKE2/pull/1 is also accurate
* https://github.com/3KeyCompany/CZERTAINLY-Appliance-Host-Config/pull/1 is not accurate => closed and open new one https://github.com/3KeyCompany/CZERTAINLY-Appliance-Host-Config/pull/2

And finally https://github.com/3KeyCompany/CZERTAINLY-Appliance/pull/2
