### ISSUE TITLE
Appliance management interface comments

### ISSUE THREAD

**Issue by jakub-moravek** [3KeyCompany/CZERTAINLY-Appliance#18]
User user interface functionality and appearance
-  Install CZERTAINLY item - must be approval before start of immediate install at least, This "head shot" stopped my heart for a while.
- Advanced options sub menu is missing Cancel button to go back to main menu
- Any change must be approved at least clicking button OK or Save.

Technical comments
-  set automated management interface startup through user default shell set up during users' creation and stored in /etc/passwd

**Comment by semik** [comment]
> set automated management interface startup through user default shell set up during users' 
> creation and stored in /etc/passwd

this means that user czertainly wont be usable for scp

**Comment by semik** [comment]
> Advanced options sub menu is missing Cancel button to go back to main menu
done https://github.com/semik/CZERTAINLY-Appliance/commit/f07dc89dcab93299ec75e639e5eb4cdca61ca09a

**Comment by semik** [comment]
> Install CZERTAINLY item - must be approval before start of immediate install at least, This "head shot" stopped my heart for a while.

done in https://github.com/semik/CZERTAINLY-Appliance/commit/55c1caf10f3141332ddceff00336cbbf15b883af
![Screenshot at 2023-02-02 14-17-26](https://user-images.githubusercontent.com/4614807/216335914-3ad943e9-1b9a-45b5-91e6-a26cc5cb93a0.png)
