### ISSUE TITLE
Create graphical interface for configuration wizard

### ISSUE THREAD

**Issue by jakub-moravek** [3KeyCompany/CZERTAINLY-Appliance#8]

**Comment by semik** [comment]
@jakub-moravek what do you think about this structure?

## Basic menu

* Configure network
* Configure certificates
* Install CZERTAINLY
* CZERTAINLY status
* Advanced options
* Exit

## Advanced menu

* Install Helm
* Install RKE2
* Install CZERTAINLY
* Remove CZERTAINLY
* Remove RKE2 & CZERTAINLY
* Enter system shell
* Reboot system

**Comment by jakub-moravek** [comment]
It looks very good.
I wold also add option to shutdown the system.

How will be ensured database user and password definition & change?

**Comment by semik** [comment]
I added DB configuration options and more.
